### ISSUE TITLE
Interrupção no execute

### ISSUE THREAD

**Issue by maykcaldas** [atoms-ufrj/playmol#1]
Tentando criar o framewok de uma zeólita LTA escrevi o código no playmol que está em anexo.

Ele lê as atribuições, o build pelo arquivo e fixa todos os átomos sem problema. Inclusive se rodar sem o execute, a zeólita é montada (conferido com o vmd). Mas quando tento o execute pra usar o pack pra copiar moléculas de água na caixa, ele interrompe o código sem terminá-lo.
[LTA_Crash.playmol.tar.gz](https://github.com/atoms-ufrj/playmol/files/143135/LTA_Crash.playmol.tar.gz)

**Comment by craabreu** [comment]
@maykcaldas, vc poderia anexar o arquivo newLTA.xyz?

**Comment by maykcaldas** [comment]
@craabreu, desculpa a demora. Só vi a mensagem agora. Achei que tinha colocado ele junto no tar.gaz.

Segue o novo anexo. O problema estava no packmol. O arquivo de input excedia o máximo de linhas permitido por padrão no mesmo, e então o programa era interrompido. Só me ocorreu de olhar o log do packmol bem depois.

[LTA_Crash.playmol.tar.gz](https://github.com/atoms-ufrj/playmol/files/238870/LTA_Crash.playmol.tar.gz)
