### ISSUE TITLE
good coordinates in lammpstrj file / bad coordinates in lmp/models data file

### ISSUE THREAD

**Issue by iurisegtovich** [atoms-ufrj/playmol#15]
# in lammpstrj
> a-uid m-uid a-type x y z
`12264 4430 CH3eoh 13.6460009 11.4874668 -84.1789017`
`12265 4430 CH2eoh 14.9055471 12.2065182 -83.9393005`
`12266 4430 Oeoh 15.1533661 13.0910788 -85.0089951`
`12267 4430 Heoh 15.9630671 13.5533257 -84.8549652`

# in lammps data
> a-uid m-uid a-type charge x y z #a-type
`12264 4430 6 0.000 15.9630671 13.5533257 -84.8549652 # CH3eoh`
`12265 4430 5 0.265 13.6460009 11.4874668 -84.1789017 # CH2eoh`
`12266 4430 4 -0.700 14.9055471 12.2065182 -83.9393005 # Oeoh`
`12267 4430 3 0.435 15.1533661 13.0910788 -85.0089951 # Heoh `

names are ok like

Ch3 Ch2 O H

so molecule is like

          3---2
               \
                O---H

but actual xyz are like

Ch2 O H CH3

so molecule is like

                 *slightly stretched bonds here
                2---O *and here
                '    \  *no bond here
                '     H   3
                '         '
                '---------'
                *ultra stretched bond here!

all left shifted 1 position, first becomes last

I'm getting a minimal case ready and will investigate

**Comment by iurisegtovich** [comment]
[minimal-bad-v7.tar.gz](https://github.com/atoms-ufrj/playmol/files/1395588/minimal-bad-v7.tar.gz)
[minimal-good-v8.tar.gz](https://github.com/atoms-ufrj/playmol/files/1395589/minimal-good-v8.tar.gz)

**Comment by iurisegtovich** [comment]
but traced to commit

```
commit b6ad3d5928c3ca15f773083784effa4213cc0f04
Author: Charlles Abreu <abreu@eq.ufrj.br>
Date:   Wed Sep 20 17:28:16 2017 -0300

    Add bonds that lie inside rigid bodies, but with model zero
```

worked fine in commit

```
commit a92818774cd699e9b706e646e0bf3529c3b722bc
Merge: a5fa3c8 c6a5d3c
Author: Charlles Abreu <abreu@eq.ufrj.br>
Date:   Wed Sep 20 00:51:02 2017 -0300

    Merge branch 'master' of https://github.com/atoms-ufrj/playmol
```

and some before

test script attached

[SERIAL-GIT-CHECKOUT-MAKE-TEST.tar.gz](https://github.com/atoms-ufrj/playmol/files/1395980/SERIAL-GIT-CHECKOUT-MAKE-TEST.tar.gz)

**Comment by craabreu** [comment]
Temporarily reverted to commit caa17c1fbf4c55b747deae7e59ab9025987d94cc
Author: Charlles Abreu <abreu@eq.ufrj.br>
Date:   Tue Sep 19 14:15:18 2017 -0300

    Use of AMBER prep file for assigning type and charge in playmoltools

A new branch was created for fixing the bug.
