### ISSUE TITLE
bug report no make install

### ISSUE THREAD

**Issue by iurisegtovich** [atoms-ufrj/playmol#2]
quando o usuario possui mais de uma versão do gtk, o script passa 3 argumentos para a função cp

cp a b c

que significa copiar o arquivo a e o arquivo b para o diretorio c

mas no caso, os argumentos a b e c gerados pelo script são: a) o arquivo original, b) o arquivo destino no diretorio destino de uma versão do gtk, c) o arquivo destino no diretorio destino de outra versao do gtk

assim na ocorrencia de o usuario ter apenas uma versão do gtk o script faz "cp a b"
mas na ocorrencia de se ter 2 versoes ele faz "cp a b c" como extrapolação automatico do cenario nao planejado
e a extraplolação lógica para esse cenario poderia ser "cp a b; cp a c"

# the error

    atoms90@atoms90-H81M-H:~/playmol$ sudo make install 
    [sudo] password for atoms90: 
    cp -f ./bin/playmol /usr/local/bin
    cp -f ./lib/packmol/packmol /usr/local/bin
    sh -x ./highlight/install.sh
    + dirname ./highlight/install.sh
    + cd ./highlight
    + pwd
    + source=/home/atoms90/playmol/highlight/gtksourceview/playmol.lang
    + locate language-specs/def.lang
    + + sed s/def.lang/playmol.lang/g
    grep usr
    + destination=/usr/share/gtksourceview-2.0/language-specs/playmol.lang
    /usr/share/gtksourceview-3.0/language-specs/playmol.lang
    + [ -z /usr/share/gtksourceview-2.0/language-specs/playmol.lang
    /usr/share/gtksourceview-3.0/language-specs/playmol.lang ]
    + which cp
    + command=/bin/cp -rf /home/atoms90/playmol/highlight/gtksourceview/playmol.lang /usr/share/gtksourceview-2.0/language-specs/playmol.lang
    /usr/share/gtksourceview-3.0/language-specs/playmol.lang
    + echo /bin/cp -rf /home/atoms90/playmol/highlight/gtksourceview/playmol.lang /usr/share/gtksourceview-2.0/language-specs/playmol.lang /usr/share/gtksourceview-3.0/language-specs/playmol.lang
    /bin/cp -rf /home/atoms90/playmol/highlight/gtksourceview/playmol.lang /usr/share/gtksourceview-2.0/language-specs/playmol.lang /usr/share/gtksourceview-3.0/language-specs/playmol.lang
    + eval /bin/cp -rf /home/atoms90/playmol/highlight/gtksourceview/playmol.lang /usr/share/gtksourceview-2.0/language-specs/playmol.lang /usr/share/gtksourceview-3.0/language-specs/playmol.lang
    + /bin/cp -rf /home/atoms90/playmol/highlight/gtksourceview/playmol.lang /usr/share/gtksourceview-2.0/language-specs/playmol.lang /usr/share/gtksourceview-3.0/language-specs/playmol.lang
    /bin/cp: target ‘/usr/share/gtksourceview-3.0/language-specs/playmol.lang’ is not a directory
    make: *** [install] Error 1

**Comment by craabreu** [comment]
Workaround: if multiple destinations are found, only the first one is used.
