### ISSUE TITLE
Error installation

### ISSUE THREAD

**Issue by fellipe-carvalho-de-oliveira** [atoms-ufrj/playmol#3]
Tentando reinstalar obtive o erro : 

gfortran -O3 -march=native -ffast-math -funroll-loops -fstrict-aliasing -cpp -Wunused -J./src/obj -c -o src/obj/mString.o src/mString.f90
gfortran -O3 -march=native -ffast-math -funroll-loops -fstrict-aliasing -cpp -Wunused -J./src/obj -c -o src/obj/mStruc.o src/mStruc.f90
gfortran -O3 -march=native -ffast-math -funroll-loops -fstrict-aliasing -cpp -Wunused -J./src/obj -c -o src/obj/mCodeFlow.o src/mCodeFlow.f90
gfortran -O3 -march=native -ffast-math -funroll-loops -fstrict-aliasing -cpp -Wunused -J./src/obj -c -o src/obj/mFix.o src/mFix.f90
gfortran -O3 -march=native -ffast-math -funroll-loops -fstrict-aliasing -cpp -Wunused -J./src/obj -c -o src/obj/mMolecule.o src/mMolecule.f90
gfortran -O3 -march=native -ffast-math -funroll-loops -fstrict-aliasing -cpp -Wunused -J./src/obj -c -o src/obj/mPackmol.o src/mPackmol.f90
gfortran -O3 -march=native -ffast-math -funroll-loops -fstrict-aliasing -cpp -Wunused -J./src/obj -c -o src/obj/mPlaymol.o src/mPlaymol.f90
src/mPlaymol.f90: In function ‘tplaymol_read_geometry’:
src/mPlaymol.f90:685:0: internal compiler error: in gfc_conv_variable, at fortran/trans-expr.c:601
Please submit a full bug report,
with preprocessed source if appropriate.
See file:///usr/share/doc/gcc-4.6/README.Bugs for instructions.
make: **\* [src/obj/mPlaymol.o] Error 1

**Comment by craabreu** [comment]
This is related to the version of gcc employed (4.6).
