### ISSUE TITLE
internal compiler error ( 1 workaround suggested )

### ISSUE THREAD

**Issue by iurisegtovich** [atoms-ufrj/playmol#4]
# ERROR
	
	segtovichisv@segtovichisv-vb-lubuntu-scicomp:~/ProgramFiles/Playmol/playmol$ make
	gfortran -O3 -march=native -ffast-math -funroll-loops -fstrict-aliasing -cpp -Wunused -J./src/obj -c -o src/obj/mMolecule.o src/mMolecule.f90
	src/mMolecule.f90:440:0:
	
	       forall (i=1:N) Coord(:,i) = matmul( A, delta(:,i) )
	 
	internal compiler error: in gfc_trans_forall_1, at fortran/trans-stmt.c:4388
	Please submit a full bug report,
	with preprocessed source if appropriate.
	See <file:///usr/share/doc/gcc-6/README.Bugs> for instructions.
	Makefile:53: recipe for target 'src/obj/mMolecule.o' failed
	make: *** [src/obj/mMolecule.o] Error 1

# GFORTRAN VERSION
	segtovichisv@segtovichisv-vb-lubuntu-scicomp:~/ProgramFiles/Playmol/playmol$ gfortran --version
	GNU Fortran (Ubuntu 6.2.0-5ubuntu12) 6.2.0 20161005
	Copyright (C) 2016 Free Software Foundation, Inc.
	This is free software; see the source for copying conditions.  There is NO
	warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# TRIAL 1 -- changing Makefile

* from
	FOPTS = -O3 -march=native -ffast-math -funroll-loops -fstrict-aliasing -cpp -Wunused
* to
	FOPTS = -g -cpp -fcheck=all

# RESULT
	
	segtovichisv@segtovichisv-vb-lubuntu-scicomp:~/ProgramFiles/Playmol/playmol$ make
	gfortran -g -cpp -fcheck=all -J./src/obj -c -o src/obj/mMolecule.o src/mMolecule.f90
	gfortran -g -cpp -fcheck=all -J./src/obj -c -o src/obj/mParser.o src/mParser.f90
	gfortran -g -cpp -fcheck=all -J./src/obj -c -o src/obj/mCodeFlow.o src/mCodeFlow.f90
	gfortran -g -cpp -fcheck=all -J./src/obj -c -o src/obj/mPackmol.o src/mPackmol.f90
	gfortran -g -cpp -fcheck=all -J./src/obj -c -o src/obj/mPlaymol.o src/mPlaymol.f90
	gfortran -g -cpp -fcheck=all -J./src/obj -c -o src/obj/playmol.o src/playmol.f90
	cd ./lib && make
	make[1]: Entering directory '/home/segtovichisv/ProgramFiles/Playmol/playmol/lib'
	tar -zxvf packmol-15.287.tar.gz
	./packmol/
	./packmol/solvate.tcl
	./packmol/feasy.f90
	./packmol/fgcommon.f90
	./packmol/initial.f90
	./packmol/molpa.f90
	./packmol/gencan.f
	./packmol/sizes.f90
	./packmol/header
	./packmol/pgencan.f90
	./packmol/LICENSE
	./packmol/io.f90
	./packmol/geasyparallel.f90
	./packmol/Makefile.default
	./packmol/COPYING
	./packmol/compindexes.f90
	./packmol/geasy.f90
	./packmol/heuristics.f90
	./packmol/AUTHORS
	./packmol/feasyparallel.f90
	./packmol/ppackmol
	./packmol/configure
	./packmol/Makefile
	./packmol/polartocart.f90
	./packmol/packmol.f90
	./packmol/usegencan.f90
	./packmol/cenmass.f90
	cd packmol && sed -i 's/\r//g' *.f90 && patch < ../packmol.patch && make && make lib
	patching file initial.f90
	patching file io.f90
	patching file main.f90
	patching file Makefile
	patching file Makefile.default
	patching file packmol.f90
	make[2]: Entering directory '/home/segtovichisv/ProgramFiles/Playmol/playmol/lib/packmol'
	 ------------------------------------------------------ 
	 Compiling packmol with /usr/bin/gfortran 
	 Flags: -O3 -ffast-math  
	 ------------------------------------------------------ 
	 ------------------------------------------------------ 
	 Packmol succesfully built.
	 ------------------------------------------------------ 
	make[2]: Leaving directory '/home/segtovichisv/ProgramFiles/Playmol/playmol/lib/packmol'
	make[2]: Entering directory '/home/segtovichisv/ProgramFiles/Playmol/playmol/lib/packmol'
	 ------------------------------------------------------ 
	 Compiling packmol with /usr/bin/gfortran 
	 Flags: -O3 -ffast-math  
	 ------------------------------------------------------ 
	 ------------------------------------------------------ 
	 Packmol succesfully built. Static library available. 
	 ------------------------------------------------------ 
	make[2]: Leaving directory '/home/segtovichisv/ProgramFiles/Playmol/playmol/lib/packmol'
	mv packmol/libpackmol.a ./
	make[1]: Leaving directory '/home/segtovichisv/ProgramFiles/Playmol/playmol/lib'
	mkdir -p ./bin
	gfortran -g -cpp -fcheck=all -J./src/obj -o bin/playmol src/obj/mBox.o src/obj/mFix.o src/obj/mMolecule.o src/obj/mParser.o src/obj/mString.o src/obj/mCodeFlow.o src/obj/mGlobal.o src/obj/mPackmol.o src/obj/mPlaymol.o src/obj/mStruc.o src/obj/playmol.o lib/libpackmol.a

# MORE ALTERNATIVES

	[FAILS] FOPTS = -O2 -march=native -ffast-math -funroll-loops -fstrict-aliasing -cpp -Wunused

	[FAILS] FOPTS = -O1 -march=native -ffast-math -funroll-loops -fstrict-aliasing -cpp -Wunused

	[BUILDS] FOPTS = -O0 -march=native -ffast-math -funroll-loops -fstrict-aliasing -cpp -Wunused

**Comment by ajsilveira** [comment]
works under gfortran 5.2

# "succesfully built"

	ana@asilveira-pc:~/playmol$ make
	mkdir -p ./src/obj
	gfortran -O3 -march=native -ffast-math -funroll-loops -fstrict-aliasing -cpp -Wunused -J./src/obj -c -o src/obj/mGlobal.o src/mGlobal.f90
	gfortran -O3 -march=native -ffast-math -funroll-loops -fstrict-aliasing -cpp -Wunused -J./src/obj -c -o src/obj/mString.o src/mString.f90
	gfortran -O3 -march=native -ffast-math -funroll-loops -fstrict-aliasing -cpp -Wunused -J./src/obj -c -o src/obj/mStruc.o src/mStruc.f90
	gfortran -O3 -march=native -ffast-math -funroll-loops -fstrict-aliasing -cpp -Wunused -J./src/obj -c -o src/obj/mMolecule.o src/mMolecule.f90
	gfortran -O3 -march=native -ffast-math -funroll-loops -fstrict-aliasing -cpp -Wunused -J./src/obj -c -o src/obj/mBox.o src/mBox.f90
	gfortran -O3 -march=native -ffast-math -funroll-loops -fstrict-aliasing -cpp -Wunused -J./src/obj -c -o src/obj/mPackmol.o src/mPackmol.f90
	gfortran -O3 -march=native -ffast-math -funroll-loops -fstrict-aliasing -cpp -Wunused -J./src/obj -c -o src/obj/mParser.o src/mParser.f90
	gfortran -O3 -march=native -ffast-math -funroll-loops -fstrict-aliasing -cpp -Wunused -J./src/obj -c -o src/obj/mCodeFlow.o src/mCodeFlow.f90
	gfortran -O3 -march=native -ffast-math -funroll-loops -fstrict-aliasing -cpp -Wunused -J./src/obj -c -o src/obj/mFix.o src/mFix.f90
	gfortran -O3 -march=native -ffast-math -funroll-loops -fstrict-aliasing -cpp -Wunused -J./src/obj -c -o src/obj/mPlaymol.o src/mPlaymol.f90
	gfortran -O3 -march=native -ffast-math -funroll-loops -fstrict-aliasing -cpp -Wunused -J./src/obj -c -o src/obj/playmol.o src/playmol.f90
	cd ./lib && make
	make[1]: Entering directory '/home/ana/playmol/lib'
	tar -zxvf packmol-15.287.tar.gz
	./packmol/
	./packmol/solvate.tcl
	./packmol/feasy.f90
	./packmol/fgcommon.f90
	./packmol/initial.f90
	./packmol/molpa.f90
	./packmol/gencan.f
	./packmol/sizes.f90
	./packmol/header
	./packmol/pgencan.f90
	./packmol/LICENSE
	./packmol/io.f90
	./packmol/geasyparallel.f90
	./packmol/Makefile.default
	./packmol/COPYING
	./packmol/compindexes.f90
	./packmol/geasy.f90
	./packmol/heuristics.f90
	./packmol/AUTHORS
	./packmol/feasyparallel.f90
	./packmol/ppackmol
	./packmol/configure
	./packmol/Makefile
	./packmol/polartocart.f90
	./packmol/packmol.f90
	./packmol/usegencan.f90
	./packmol/cenmass.f90
	cd packmol && sed -i 's/\r//g' *.f90 && patch < ../packmol.patch && make && make lib
	patching file initial.f90
	patching file io.f90
	patching file main.f90
	patching file Makefile
	patching file Makefile.default
	patching file packmol.f90
	make[2]: Entering directory '/home/ana/playmol/lib/packmol'
	 ------------------------------------------------------ 
	 Compiling packmol with /usr/bin/gfortran 
	 Flags: -O3 -ffast-math  
	 ------------------------------------------------------ 
	 ------------------------------------------------------ 
	 Packmol succesfully built.
	 ------------------------------------------------------ 
	make[2]: Leaving directory '/home/ana/playmol/lib/packmol'
	make[2]: Entering directory '/home/ana/playmol/lib/packmol'
	 ------------------------------------------------------ 
	 Compiling packmol with /usr/bin/gfortran 
	 Flags: -O3 -ffast-math  
	 ------------------------------------------------------ 
	 ------------------------------------------------------ 
	 Packmol succesfully built. Static library available. 
	 ------------------------------------------------------ 
	make[2]: Leaving directory '/home/ana/playmol/lib/packmol'
	mv packmol/libpackmol.a ./
	make[1]: Leaving directory '/home/ana/playmol/lib'
	mkdir -p ./bin
	gfortran -O3 -march=native -ffast-math -funroll-loops -fstrict-aliasing -cpp -Wunused -J./src/obj -o bin/playmol src/obj/mPackmol.o src/obj/mPlaymol.o src/obj/mMolecule.o src/obj/mGlobal.o src/obj/mString.o src/obj/mParser.o src/obj/playmol.o src/obj/mStruc.o src/obj/mFix.o src/obj/mBox.o src/obj/mCodeFlow.o lib/libpackmol.a

# gfortran version
	ana@asilveira-pc:~/playmol$ gfortran --version
	GNU Fortran (Ubuntu 5.2.1-22ubuntu2) 5.2.1 20151010
	Copyright (C) 2015 Free Software Foundation, Inc.

	GNU Fortran comes with NO WARRANTY, to the extent permitted by law.
	You may redistribute copies of GNU Fortran
	under the terms of the GNU General Public License.
	For more information about these matters, see the file named COPYING

**Comment by craabreu** [comment]
Command replaced by: Coord = matmul( A, delta )
